<h1 class="title title-main">Bienvenue au cabinet chiropratique</h1>
<section class="presentation">
  <h2 class="title title-presentation">La chiro pourquoi ?</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <div class="presentation-list">
    <article class="why-presentation">
      <img src="<?= $wwwUrl ?>/images/picto/icons_colonne.png" class="picto-presentation" alt="picto douleurs colonne vertebrale traités par la chiropraxie">
      <h3 class="title title-article">Douleurs à la colonne</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
    <article class="why-presentation">
      <img src="<?= $wwwUrl ?>/images/picto/icons_articulaire.png" class="picto-presentation" alt="picto douleurs articulaires traités par la chiropraxie">
      <h3 class="title title-article">Douleurs articulaires</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
    <article class="why-presentation">
      <img src="<?= $wwwUrl ?>/images/picto/icons_symptome.png" class="picto-presentation" alt="picto autres symptômes traités par la chiropraxie">
      <h3 class="title title-article">Autre symptômes</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
    <article class="why-presentation">
      <img src="<?= $wwwUrl ?>/images/picto/icons_prevention.png" class="picto-presentation" alt="picto traitement chiropratique en prévention">
      <h3 class="title title-article">Bien être et prévention</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
  </div>
  <a class="cta" href="<?= $requestUrl ?>"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
</section>
<div class="slider">

</div>
<section class="presentation">
  <h2 class="title title-presentation">La chiro pour qui ?</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <div class="presentation-list">
    <article class="who-presentation">
      <img src="<?= $wwwUrl ?>/images/patients/baby.png" class="img-patients" alt="La chiropraxie pour les bébés">
      <h3 class="title title-article">Les nouveaux nés</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
    <article class="who-presentation">
      <img src="<?= $wwwUrl ?>/images/patients/pregnant.jpg" class="img-patients" alt="La chiropraxie pour les femmes enceintes">
      <h3 class="title title-article">Les femmes enceintes</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
    <article class="who-presentation">
      <img src="<?= $wwwUrl ?>/images/patients/kids.jpg" class="img-patients" alt="La chiropraxie pour les enfants et adolescents">
      <h3 class="title title-article">Les enfants et adolescents</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
    <article class="who-presentation">
      <img src="<?= $wwwUrl ?>/images/patients/seniors.jpg" class="img-patients" alt="La chiropraxie pour les séniors">
      <h3 class="title title-article">Les séniors</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
    <article class="who-presentation">
      <img src="<?= $wwwUrl ?>/images/patients/adults.jpg" class="img-patients" alt="La chiropraxie pour les adultes">
      <h3 class="title title-article">Les adultes</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
    <article class="who-presentation">
      <img src="<?= $wwwUrl ?>/images/patients/sports.jpg" class="img-patients" alt="La chiropraxie pour les sportifs">
      <h3 class="title title-article">Les sportifs</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </article>
  </div>
  <a class="cta" href="<?= $requestUrl ?>"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
</section>
